import sys
import os
import json
from datetime import datetime, date
from unittest.mock import patch, MagicMock

# Add backend to sys.path
sys.path.append(os.path.join(os.getcwd(), "backend"))

from db.database import get_db_sync, HeavyCompany, HeavyRun, HeavyRunArticle
from sqlalchemy import select, delete

# Define mock articles matching our criteria
mock_articles = [
    {
        "id": 101,
        "title": "Google India CEO Sundar Pichai announces new investments in startup ecosystem",
        "url": "https://example.com/art1",
        "published_at": datetime.utcnow().isoformat(),
        "full_body": "Full body text about Google India CEO Sundar Pichai announcing new startup investments.",
        "summary": "Google India CEO Sundar Pichai announced new startup investments.",
        "agency": "PTI",
        "sector": "google"
    },
    {
        "id": 102,
        "title": "YouTube India launches new creator safety tools for video uploads",
        "url": "https://example.com/art2",
        "published_at": datetime.utcnow().isoformat(),
        "full_body": "Full body text about YouTube India launching creator safety features.",
        "summary": "YouTube India launched creator safety features.",
        "agency": "The Indian Express",
        "sector": "google"
    },
    {
        "id": 103,
        "title": "CCI fines Google India for dominant position in Android app market",
        "url": "https://example.com/art3",
        "published_at": datetime.utcnow().isoformat(),
        "full_body": "Full body text about CCI dominant position fines on Google.",
        "summary": "CCI fined Google for dominant position.",
        "agency": "Reuters India",
        "sector": "google"
    }
]

def run_pass(llm_judge_enabled: bool):
    print(f"\n" + "="*50)
    print(f"RUNNING TEST PASS: llm_judge_enabled = {llm_judge_enabled}")
    print("="*50)
    
    db = get_db_sync().__enter__()
    
    # Clean up existing test companies
    db.execute(delete(HeavyCompany).where(HeavyCompany.name == "Test Google Corp"))
    db.commit()
    
    # Create test company with Pooja folder filtering enabled
    company = HeavyCompany(
        name="Test Google Corp",
        sector_match="google,ai",
        enabled=True,
        timezone="Asia/Kolkata",
        fetch_time="07:00",
        window_hours=24,
        relevance_threshold=0.5,
        pooja_folder_filtering_enabled=True,
        llm_judge_enabled=llm_judge_enabled
    )
    db.add(company)
    db.commit()
    db.refresh(company)
    company_id = company.id
    print(f"Created company ID: {company_id}")

    # Mock response from Nexus remote feed
    mock_resp = MagicMock()
    mock_resp.json.return_value = {
        "articles": mock_articles,
        "total_pages": 1
    }
    mock_resp.raise_for_status = MagicMock()

    # Setup LLM mocks
    mock_verify = MagicMock(return_value=True)
    mock_summary = MagicMock(return_value="Mock Executive Summary")
    mock_takeaways = MagicMock(return_value="Mock Strategic Takeaways")

    print("Running pipeline run_heavy_automation_task...")
    with patch('requests.get', return_value=mock_resp), \
         patch('scraper.heavy_llm.verify_article_keyword_with_claude', mock_verify), \
         patch('scraper.heavy_llm.generate_executive_summary', mock_summary), \
         patch('scraper.heavy_llm.generate_strategic_takeaways', mock_takeaways), \
         patch('scraper.heavy_llm.summarize_article', return_value="Mock summary generated by Hugging Face router."), \
         patch('utils.email.send_report_email', return_value=True):
         
        from scraper.tasks import run_heavy_automation_task
        success = run_heavy_automation_task(company_id)
        
    print(f"Task completion status: {success}")
    assert success is True, "Pipeline failed to run successfully!"

    # Verify the results in database
    run_rec = db.execute(
        select(HeavyRun)
        .where(HeavyRun.company_id == company_id)
        .order_by(HeavyRun.started_at.desc())
    ).scalars().first()
    
    assert run_rec is not None, "No HeavyRun record was created!"
    print(f"Run ID: {run_rec.id}, Status: {run_rec.status}")

    # Verify summary contents based on toggle
    if llm_judge_enabled:
        # Should have called verification and summarization
        assert mock_verify.call_count > 0, "Claude relevance verification should have been called!"
        assert mock_summary.call_count > 0, "Claude summary generation should have been called!"
        print("[PASS] Claude summarization and verification were correctly executed.")
    else:
        # Should have skipped both and used placeholders
        assert mock_verify.call_count == 0, "Claude relevance verification should NOT have been called!"
        assert mock_summary.call_count == 0, "Claude summary generation should NOT have been called!"
        print("[PASS] Claude summarization and verification were correctly bypassed.")

    # Clean up test company
    db.execute(delete(HeavyCompany).where(HeavyCompany.id == company_id))
    db.commit()
    print("Cleaned up test database company.")

def main():
    try:
        # Run test with Claude toggle turned OFF
        run_pass(llm_judge_enabled=False)
        
        # Run test with Claude toggle turned ON
        run_pass(llm_judge_enabled=True)
        
        print("\n" + "="*50)
        print("ALL TEST PASSES COMPLETED SUCCESSFULLY!")
        print("="*50)
        return 0
    except Exception as e:
        print(f"\n[ERROR] Pipeline verification failed: {e}")
        import traceback
        traceback.print_exc()
        return 1

if __name__ == "__main__":
    sys.exit(main())
